version: "2.3"
services:
  unifi:
    container_name: unifi
    image: jacobalberty/unifi:stable
    volumes:
      - ./unifi:/unifi
    init: true
    restart: always
    ports:
      - "${HOST_IP}:443:443"
      - "${HOST_IP}:8880:8880"
      - "${HOST_IP}:8443:8443"
      - "${HOST_IP}:8080:8080"
      - "${HOST_IP}:3478:3478/udp"
      - "${HOST_IP}:10001:10001/udp"
    environment:
      RUNAS_UID0: "false"
      TZ: "America/New_York"
